import "./globals.css";
import { cookies } from "next/headers";
import { I18nProviderClient } from "@/locales/client";
import { UserProvider } from "@auth0/nextjs-auth0/client";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

export default function RootLayout({ children, params: { locale } }: Props) {
  const theme = cookies().get("theme");

  return (
    <html
      lang={locale}
      className={`${theme ? theme.value : ""} !scroll-smooth`}
    >
      <UserProvider>
        <body className="bg-body dark:bg-dark-primary">
          <I18nProviderClient locale={locale}>{children}</I18nProviderClient>
        </body>
      </UserProvider>
    </html>
  );
}
